_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: da9b614e-0f9f-41de-a3fe-a5f01b82d541
name: Quarantie
mail: admin@example.com
slogan: 'Software Development'
page:
  403: ''
  404: ''
  front: /node/12
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
